name: wikinias
description: "An Android app for Nias Wikipedia, Wiktionary and Wikibooks"
publish_to: 'none'
version: 2.5.0+15

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  beautiful_soup_dart: ^0.3.0
  easy_localization: ^3.0.8
  flutter_riverpod: ^3.2.1
  flutter_widget_from_html: ^0.17.2
  google_fonts: ^8.0.2
  html: ^0.15.6
  http: ^1.6.0
  just_audio: ^0.10.4
  shared_preferences: ^2.5.5
  share_plus: ^13.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  wikimedia_core:
    path: packages/wikimedia_core
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/images/onboarding1.webp
    - assets/images/onboarding2.webp
    - assets/images/onboarding3.webp
    - assets/images/onboarding4.webp
    - assets/images/onboarding5.webp
    - assets/translations/
    - assets/translations/en.json
    - assets/translations/id.json
    - assets/translations/nia.json
